// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_OUNm4DbN25twKZ-w9QuiLLjJXQhyyTs',
    appId: '1:1035941947717:web:4d68e393927c683d0e362c',
    messagingSenderId: '1035941947717',
    projectId: 'saksi-182ac',
    authDomain: 'saksi-182ac.firebaseapp.com',
    storageBucket: 'saksi-182ac.firebasestorage.app',
    measurementId: 'G-EKSKEMXZ6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzCDWvRpj28gkk1ynsnKt_PMWPjcLxkGw',
    appId: '1:1035941947717:android:2bc30550847a656c0e362c',
    messagingSenderId: '1035941947717',
    projectId: 'saksi-182ac',
    storageBucket: 'saksi-182ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI4fzR0bM9k_xbRmmfOWbxmKtNdnOXLME',
    appId: '1:1035941947717:ios:f4e30802b51cd44c0e362c',
    messagingSenderId: '1035941947717',
    projectId: 'saksi-182ac',
    storageBucket: 'saksi-182ac.firebasestorage.app',
    androidClientId: '1035941947717-1gbdr60lrq8ten0r8s8keioa4b71d2gs.apps.googleusercontent.com',
    iosClientId: '1035941947717-b16c8cqijrelv4bv1r7pcfv8udioa3jm.apps.googleusercontent.com',
    iosBundleId: 'com.example.saksiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI4fzR0bM9k_xbRmmfOWbxmKtNdnOXLME',
    appId: '1:1035941947717:ios:f4e30802b51cd44c0e362c',
    messagingSenderId: '1035941947717',
    projectId: 'saksi-182ac',
    storageBucket: 'saksi-182ac.firebasestorage.app',
    androidClientId: '1035941947717-1gbdr60lrq8ten0r8s8keioa4b71d2gs.apps.googleusercontent.com',
    iosClientId: '1035941947717-b16c8cqijrelv4bv1r7pcfv8udioa3jm.apps.googleusercontent.com',
    iosBundleId: 'com.example.saksiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_OUNm4DbN25twKZ-w9QuiLLjJXQhyyTs',
    appId: '1:1035941947717:web:4d68e393927c683d0e362c',
    messagingSenderId: '1035941947717',
    projectId: 'saksi-182ac',
    authDomain: 'saksi-182ac.firebaseapp.com',
    storageBucket: 'saksi-182ac.firebasestorage.app',
    measurementId: 'G-EKSKEMXZ6H',
  );

}